server:
  port: 8080

spring:
  application:
    name: api-gateway
  
  cloud:
    gateway:
      routes:
        # User Service Routes
        - id: user-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/users/**
          filters:
            - name: CircuitBreaker
              args:
                name: user-service
                fallbackUri: forward:/fallback/user
        
        - id: user-graphql
          uri: http://localhost:8081
          predicates:
            - Path=/graphql
            - Header=X-Service, user
          filters:
            - name: CircuitBreaker
              args:
                name: user-graphql
                fallbackUri: forward:/fallback/user
        
        # Account Service Routes
        - id: account-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/accounts/**
          filters:
            - name: CircuitBreaker
              args:
                name: account-service
                fallbackUri: forward:/fallback/account
        
        - id: account-graphql
          uri: http://localhost:8082
          predicates:
            - Path=/graphql
            - Header=X-Service, account
          filters:
            - name: CircuitBreaker
              args:
                name: account-graphql
                fallbackUri: forward:/fallback/account
        
        # Transaction Service Routes
        - id: transaction-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/transactions/**
          filters:
            - name: CircuitBreaker
              args:
                name: transaction-service
                fallbackUri: forward:/fallback/transaction
        
        - id: transaction-graphql
          uri: http://localhost:8083
          predicates:
            - Path=/graphql
            - Header=X-Service, transaction
          filters:
            - name: CircuitBreaker
              args:
                name: transaction-graphql
                fallbackUri: forward:/fallback/transaction
        
        # Health Check Routes
        - id: user-health
          uri: http://localhost:8081
          predicates:
            - Path=/health/user
          filters:
            - RewritePath=/health/user, /actuator/health
        
        - id: account-health
          uri: http://localhost:8082
          predicates:
            - Path=/health/account
          filters:
            - RewritePath=/health/account, /actuator/health
        
        - id: transaction-health
          uri: http://localhost:8083
          predicates:
            - Path=/health/transaction
          filters:
            - RewritePath=/health/transaction, /actuator/health
        
        # Gateway Health Check
        - id: gateway-health
          uri: http://localhost:8080
          predicates:
            - Path=/health
          filters:
            - RewritePath=/health, /actuator/health

      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOriginPatterns: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true

# Circuit Breaker Configuration
resilience4j:
  circuitbreaker:
    instances:
      user-service:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10
      account-service:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10
      transaction-service:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10

# Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,gateway
  endpoint:
    health:
      show-details: always

# Logging Configuration
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web: DEBUG
    com.graphbanking.apigateway: DEBUG 