version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_DB: graphbanking
      POSTGRES_USER: graphbanking
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - banking-network

  # Redis for API Gateway
  redis:
    image: redis:7-alpine
    container_name: redis-cache
    ports:
      - "6379:6379"
    networks:
      - banking-network

  # User Service
  user-service:
    build: ../user-service
    container_name: user-service
    ports:
      - "8081:8081"
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/graphbanking
      - SPRING_DATASOURCE_USERNAME=graphbanking
      - SPRING_DATASOURCE_PASSWORD=password
    networks:
      - banking-network

  # Account Service
  account-service:
    build: ../account-service
    container_name: account-service
    ports:
      - "8082:8082"
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/graphbanking
      - SPRING_DATASOURCE_USERNAME=graphbanking
      - SPRING_DATASOURCE_PASSWORD=password
    networks:
      - banking-network

  # Transaction Service
  transaction-service:
    build: ../transaction-service
    container_name: transaction-service
    ports:
      - "8083:8083"
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/graphbanking
      - SPRING_DATASOURCE_USERNAME=graphbanking
      - SPRING_DATASOURCE_PASSWORD=password
    networks:
      - banking-network

  # API Gateway
  api-gateway:
    build: .
    container_name: api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - user-service
      - account-service
      - transaction-service
      - redis
    environment:
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
    networks:
      - banking-network

volumes:
  postgres_data:

networks:
  banking-network:
    driver: bridge 